jobs: 50
cluster: "sbatch --parsable -p {params.partition} -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o Cluster_logs/{rule}_{wildcards}-%j.out -e Cluster_logs/{rule}_{wildcards}-%j.err --mail-type=FAIL --mail-user=loic.talignani@ird.fr"
default-resources: [cpus=1, mem_mb=8000, time_min=15000]
resources: [cpus=30, mem_mb=400000]
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 8
latency-wait: 600
keep-going: true
rerun-incomplete: true
printshellcmds: true
scheduler: greedy
cluster-status: status-sacct.sh
#use-conda: true
#conda-frontend: conda

