###############################################################################
# Author: Loïc TALIGNANI
# Affiliation: IRD_MIVEGEC / Université de Montpellier
# Aim: Configuration file for shave.smk snakefile
# Date: 2022.10.05
# Use: Edit or de/comment (#) settings
# Latest modification: 2022.11.24
# Done:
###############################################################################
### RESOURCES ----------------------------------------------------------------------------------------
samples: config/samples.tsv
units: config/units.tsv

### MODULES ------------------------------------------------------------------------------------------
MODULES:
  BCFTOOLS: "module load bcftools/1.15.1"
  BWA: "module load bwa/0.7.17"
  FASTQC: "module load fastqc/0.11.8"
  FASTQSCREEN: "module load fastq-screen/0.13.0"
  PICARDTOOLS: "module load picard/2.23.5"
  GATK4: "module load gatk4/4.2.6.1"
  GRAPHVIZ: "module load graphviz/2.40.1"
  HTSLIB: "module load htslib/1.14"
  JAVA8: "module load java-jdk/8.0.112"
  MULTIQC: "module load multiqc/1.13"
  PYTHON3: "module load python/3.7"
  QUALIMAP: "module load qualimap/2.2.2b"
  SAMTOOLS: "module load samtools/1.15.1"
  SNAKEMAKE: "module load snakemake/7.7.0"
  TRIMMOMATIC: "module load trimmomatic/0.39 "
  VCFTOOLS: "module load vcftools/0.1.16"

### TRIMMING --------------------------------------------------------------------------------------
trimming:
  # If you activate trimming by setting this to `True`, this mean that the
  # reads have been already trimmed. You will have to specify the respective
  # Trimmomatic adapter trimming flag for each unit in the `units.tsv` file's
  # `adapters` column
  activate: False

trimmomatic:
  adapters:
    nextera: "resources/adapters/NexteraPE-PE.fa"
    truseq2-pe: "resources/adapters/TruSeq2-PE.fa"
    truseq2-se: "resources/adapters/TruSeq2-SE.fa"
    truseq3-pe: "resources/adapters/TruSeq3-PE.fa"
    truseq3-pe-2: "resources/adapters/TruSeq3-PE-2.fa"
    truseq3-se: "resources/adapters/TruSeq3-SE.fa"
  seedMisMatches: 2
  palindromeClipTreshold: 30
  simpleClipThreshold: 15
  LeadMinTrimQual: 3
  TrailMinTrimQual: 3
  windowSize: 4
  avgMinQual: 15
  minReadLength: 50
  phred: "-phred33"

### REFERENCE ----------------------------------------------------------------------------------------
ref:
  ref_name: "Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4"
  path: "resources/genomes/" # Path to genomes references
  reference: "resources/genomes/Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa" # Your reference, in fasta format
  index: "Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa.fai"
  dictionary: "Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.dict"
## Available options:
## 'GCA_018104305.1_AalbF3_genomic.fasta'                       # AalbF3
## 'Anopheles-gambiae-PEST_CHROMOSOMES_AgamP4.fa'               # AgamP4

### PROCESSING ----------------------------------------------------------------------------------------
resources:
  tmpdir: "$TMPDIR" # Temporary directory (default: '$TMPDIR')
  ## Examples:
  ## '$TMPDIR'  # System variable $TMPDIR (dafault)
  ## '.'        # Local (i.e. GeVarLi root directory)
  ## '/scratch' # HPC (set it to match your HPC usage)

### ENVIRONNEMENTS -----------------------------------------------------------------------------------
# conda:
#   Linux: # Conda Linux environement yaml files:
#     bcftools: "workflow/envs/linux/bcftools-1.15.1.yaml" # Bcftools     ver. 1.15.1
#     bedtools: "workflow/envs/linux/bedtools-2.30.0.yaml" # Bedtools     ver. 2.30.0
#     bowtie2: "workflow/envs/linux/bowtie2-2.4.5.yaml" # Bowtie2      ver. 2.4.5
#     bwa: "workflow/envs/linux/bwa-0.7.17.yaml" # BWA          ver. 0.7.17
#     fastq-screen: "workflow/envs/linux/fastq-screen-0.15.2.yaml" # Fastq-Screen ver. 0.15.2
#     fastqc: "workflow/envs/linux/fastqc-0.11.9.yaml" # FastQC       ver. 0.11.9
#     gawk: "workflow/envs/linux/gawk-5.1.0.yaml" # Awk          ver. 5.1.0
#     multiqc: "workflow/envs/linux/multiqc-1.12.yaml" # MultiQC      ver. 1.12
#     samtools: "workflow/envs/linux/samtools-1.15.1.yaml" # Samtools     ver. 1.15.1
#     gatk: "workflow/envs/linux/gatk-3.8.yaml" # gatk ver. 3.8
#     gatk4: "workflow/envs/linux/gatk-4.3.0.0.yaml" # gatk ver. 4.3.0.0
#     picard: "workflow/envs/linux/picard-2.27.5.yaml" # picard ver. 2.27.5
#     qualimap: "workflow/envs/linux/qualimap-2.2.2.yaml" # Qualimap    vers. 2.2.2
#     trimmomatic: "workflow/envs/linux/trimmomatic-0.39.yaml" # trimmomatic ver. 0.39

### GATK ---------------------------------------------------------------------------------------------
gatk:
  genomicsdbimport: ""
  genotypegvcfs: "-include-non-variant-sites"
  haplotypecaller: "-ERC GVCF --output-mode EMIT_ALL_CONFIDENT_SITES"
## Available options:  "-ERC GVCF"                              Emit Ref Confidence scores with condensed non-variants blocks, ie the GVCF format
##                     "-ERC BP_RESOLUTION"                     Emit Ref Confidence scores site by site
##                     "--output-mode EMIT_VARIANTS_ONLY"       Produces calls only at variant sites
##                     "--output-mode EMIT_ALL_ACTIVE_SITES"    Produces calls at any region over the activity threshold regardless of confidence. This will give a measure of reference confidence and a measure of which alt alleles are more plausible. Inflate VCF size considerably
##                     "--output-mode EMIT_ALL_CONFIDENT_SITES" Produces calls at variant sites and confident reference sites

### KNWON VARIATION SITES ----------------------------------------------------------------------------
knwon_variation: False

alleles:
  alleles_target: "--alleles xxxx"

### BWA ----------------------------------------------------------------------------------------------
bwa:
  path: "resources/indexes/bwa/" # Path to BWA indexes

### FASTQSCREEN --------------------------------------------------------------------------------------
fastq-screen:
  config: "config/fastq-screen.conf" # Path to the fastq-screen configuration file
  subset: 1000 # Don't use the whole sequence file, but sub-dataset of specified number of read (default: '1000') [INT] (0='all')
  aligner: "bwa" # Aligner for fastq-screen (default and should be 'bwa')
  ## Available options:
  ## 'bwa'     # Burrows-Wheeler Aligner (default, somme small genomes indexes provided, see 'fastq-screen.conf')
  ## 'bowtie'  # Bowtie (indexes not provided)
  ## 'bowtie2' # Bowtie2 (indexes not provided)

### VARIANTFILTRATION --------------------------------------------------------------------------------
filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: False
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      {
        "myfilter": "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0",
      }
    indels: { "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0" }
